import os 
from dotenv import load_dotenv

load_dotenv(override=True)

GEMINI_API_KEY=os.getenv("GEMINI_API_KEY")
IMAGEKIT_PRIVATE_KEY=os.getenv("IMAGEKIT_PRIVATE_KEY")
IMAGEKIT_PUBLIC_KEY=os.getenv("IMAGEKIT_PUBLIC_KEY")
IMAGEKIT_URL_ENDPOINT=os.getenv("IMAGEKIT_URL_ENDPOINT")
SUPABASE_PROJECT_URL=os.getenv("SUPABASE_PROJECT_URL")
SUPABASE_SERVICE_ROLE_KEY=os.getenv("SUPABASE_SERVICE_ROLE_KEY")
SUPABASE_ANON_KEY=os.getenv("SUPABASE_ANON_KEY")
SUPABASE_JWT_SECRET=os.getenv("SUPABASE_JWT_SECRET")


if not all ([GEMINI_API_KEY,IMAGEKIT_PRIVATE_KEY,IMAGEKIT_PUBLIC_KEY,IMAGEKIT_URL_ENDPOINT,SUPABASE_PROJECT_URL,SUPABASE_SERVICE_ROLE_KEY,SUPABASE_ANON_KEY,SUPABASE_JWT_SECRET]):
    print("Environment Key Missing")